### ISSUE TITLE
Estudar Tailwind

### ISSUE THREAD

**Issue by FerreiraLarissa** [luuishenriique/GATE#16]
Eu como desenvolvedor gostaria de aprender a usar o tailwind para utilizar com laravel.

**Comment by Mateuslpds** [comment]
Estou estudando os conceitos do Tailwind e já aplicando no contexto da página inicial. No momento estou tendo problemas apenas com a customização da paleta de cores do Tailwind.

**Comment by Mateuslpds** [comment]
Criamos um novo repositório que usaremos para estudar o Tailwind

**Comment by Mateuslpds** [comment]
[https://github.com/Mateuslpds/TailWindPEP2](url)

**Comment by Mateuslpds** [comment]
[https://github.com/Mateuslpds/TailWindPEP2](url)

**Comment by KaueLui** [comment]
Protótipo da tela inicial (Tailwind)
![image](https://user-images.githubusercontent.com/49284929/106623819-c531d380-6553-11eb-8592-1db073f82d9c.png)

**Comment by KaueLui** [comment]
Protótipo da tela inicial (Tailwind)

https://user-images.githubusercontent.com/49284929/106628845-fb258680-6558-11eb-9d1d-6e7eabecb170.mp4

**Comment by KaueLui** [comment]
Protótipo da tela inicial 2

https://user-images.githubusercontent.com/49284929/106633875-fa432380-655d-11eb-820f-5fba401e7ba8.mp4

**Comment by lilialnas** [comment]
A primeira opção é mais interessante.
