### ISSUE TITLE
Criação do modelo de banco de dados

### ISSUE THREAD

**Issue by lilialnas** [luuishenriique/GATE#5]
Eu como desenvolvedor quero criar o modelo de dados para definir as entidades do sistema.

**Comment by luuishenriique** [comment]
![Fluxo de ações GATE ](https://user-images.githubusercontent.com/49295189/104529819-5a8f1700-55e9-11eb-85f5-724395a80388.png)

### Fluxo de ações para modelo de criação das entidades e dos relacionamentos do banco de dados.
